#ifndef ATOLLA_ERROR_CODES
#define ATOLLA_ERROR_CODES

#define ATOLLA_ERROR_CODE_NOT_BORROWED 0
#define ATOLLA_ERROR_CODE_REQUESTED_BUFFER_TOO_LARGE 1
#define ATOLLA_ERROR_CODE_REQUESTED_FRAME_DURATION_TOO_SHORT 2
#define ATOLLA_ERROR_CODE_LENT_TO_OTHER_SOURCE 3
#define ATOLLA_ERROR_CODE_BAD_MSG 4
#define ATOLLA_ERROR_CODE_TIMEOUT 5

#endif // ATOLLA_ERROR_CODES
