#ifndef ATOLLA_VERSION
#define ATOLLA_VERSION

#define ATOLLA_VERSION_PROTOCOL_MAJOR 1
#define ATOLLA_VERSION_PROTOCOL_MINOR 1

#define ATOLLA_VERSION_LIBRARY_MAJOR 1
#define ATOLLA_VERSION_LIBRARY_MINOR 1
#define ATOLLA_VERSION_LIBRARY_PATCH 0

#endif // ATOLLA_VERSION
